### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by bryankenote**
#1 
Also setup prettier and tslint.

### CODE REVIEW

**Comment by bryankenote** [comment]
hmmm... my build is not producing these errors. What version of node are you using?

**Comment by timothy-b** [comment]
>What version of node are you using?

Those error messages weren't from node, but from `tsc`. I think my [accidental duplicate `program.js`](https://github.com/timothy-b/IOT-SEC/commit/0e42262935b6d5ddfe3151a63a75c0cc53f341c7) might have confused you; AFAIK you can't run straight typescript with node, but have to use `tsc` to transpile it, or execute it with `ts-node` or `deno`.

**Comment by bryankenote** [comment]
The errors you are seeing are that node modules are failing to be resolved. I set the module resolution to node, although this should be the default anyway. also, did you forget to `npm install`? It looks like you warnings that node types have not been installed and they are in the package.json.

**Comment by timothy-b** [comment]
>did you forget to npm install

💡
apologies for the shabby late-night review and thanks for your work!

**Pull request merged**
